name: 'spring-boot-mini-banking'
services:
  mini-banking-db:
    image: postgres:17-alpine
    container_name: mini-banking-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini-banking-db
    ports:
      - "15432:5432"
    volumes:
      - mini-banking-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 500m
volumes:
  mini-banking-db-data: